"""Add DevicePanelMapping and update IoTDevice site_id

Revision ID: 6eaa5ecf6cf1
Revises: 
Create Date: 2026-09-19 11:36:38.146065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eaa5ecf6cf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iot_devices', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_iot_devices_device_token'), 'iot_devices', ['device_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iot_devices_device_token'), table_name='iot_devices')
    op.alter_column('iot_devices', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
